name: solar-burst-multiview
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - astropy
  - sunpy
  - requests
  - pyvo
  - pip
  - pip:
    - stixdcpy          # STIX data client
    - ecallisto-ng      # e-Callisto data access
    - mwalib            # MWA metadata
